### ISSUE TITLE
[bug] homepage error

### ISSUE THREAD

**Issue by zbtzbtzbt** [hologres/hologres-issues#2]
http://hologres.io/ 这个网站打开是购物网站。。。

**Comment by lifanxi** [comment]
Hologres独立网站已经下线，您可以访问Hologres产品在阿里云官网的页面了解产品的相关信息：
https://www.aliyun.com/product/bigdata/hologram

**Comment by lifanxi** [comment]
已修改GitHub Hologres组织配置，将主页URL改为阿里云官网页面。
